@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <div class="gym-dashboard-heading"><div><h1>Bem-vindo de volta, {{ auth()->user()->name }}!</h1><p>Acompanhe seu plano, treino e evolução na academia.</p></div><div class="gym-dashboard-meta"><span class="gym-dashboard-eyebrow">{{ now()->locale('pt_BR')->translatedFormat('l, d \\d\\e F \\d\\e Y') }}</span><span class="gym-dashboard-motto">"Disciplina hoje, resultados sempre!" <i class="bi bi-universal-access"></i></span></div></div>
@stop

@section('content')
    <x-alerts />
    <div class="gym-dashboard-metrics">
        <div class="gym-metric gym-metric-primary"><i class="bi bi-journal-check"></i><span>Minha matrícula</span><strong>{{ $studentEnrollment ? 'Ativa' : '—' }}</strong><small>{{ $studentEnrollment?->plan?->name ?? 'Nenhum plano vigente' }}</small></div>
        <div class="gym-metric gym-metric-success"><i class="bi bi-clipboard2-pulse"></i><span>Treinos ativos</span><strong>{{ $studentWorkoutCount }}</strong><small>Fichas disponíveis</small></div>
        <div class="gym-metric gym-metric-warning"><i class="bi bi-calendar-check"></i><span>Frequência no mês</span><strong>{{ $studentAttendanceCount }}</strong><small>Presenças registradas</small></div>
        <div class="gym-metric gym-metric-danger"><i class="bi bi-wallet2"></i><span>Contas pendentes</span><strong>{{ $studentPendingTransactions->count() }}</strong><small>Parcelas a acompanhar</small></div>
    </div>

    <div class="row gym-dashboard-overview"><div class="col-12 col-xl-7"><div class="card gym-dashboard-panel h-100"><div class="card-header"><span class="gym-panel-icon text-primary"><i class="bi bi-clipboard2-pulse"></i></span><div class="gym-panel-heading"><h3 class="card-title">Meu treino atual</h3><small>Ficha destinada a você</small></div><a href="{{ route('student-workout.history') }}" class="gym-view-all">Ver histórico <i class="bi bi-arrow-right"></i></a></div><div class="card-body">
        @if ($workoutPlan)<h3 class="h5 mb-1">{{ $workoutPlan->name }}</h3><p class="text-muted">Instrutor: {{ $workoutPlan->teacher?->name ?? '-' }}</p>@forelse ($workoutPlan->exercises as $workoutExercise)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $workoutExercise->exercise?->name ?? 'Exercício' }}</span><small class="text-muted">{{ $workoutExercise->sets }} séries · {{ $workoutExercise->repetitions }} repetições</small></div>@empty<p class="text-muted mb-0">Sua ficha ainda não possui exercícios.</p>@endforelse @else<p class="text-muted mb-0">Nenhuma ficha de treino ativa disponível.</p>@endif
    </div></div></div><div class="col-12 col-xl-5"><div class="card gym-dashboard-panel h-100"><div class="card-header"><span class="gym-panel-icon text-success"><i class="bi bi-lightning-charge-fill"></i></span><div class="gym-panel-heading"><h3 class="card-title">Ações rápidas</h3><small>Acesse seus dados</small></div></div><div class="card-body d-grid gap-2"><a href="{{ route('students.me') }}" class="gym-action"><i class="bi bi-person-circle text-primary"></i><span><strong>Meu perfil</strong><small>Consultar meus dados cadastrais</small></span><i class="bi bi-chevron-right ms-auto"></i></a><a href="{{ route('student-enrollment.history') }}" class="gym-action"><i class="bi bi-journal-check text-success"></i><span><strong>Minha matrícula</strong><small>Ver plano e período contratado</small></span><i class="bi bi-chevron-right ms-auto"></i></a><a href="{{ route('student-attendance.create') }}" class="gym-action"><i class="bi bi-calendar-plus text-info"></i><span><strong>Registrar treino</strong><small>Escolher a unidade de atendimento</small></span><i class="bi bi-chevron-right ms-auto"></i></a></div></div></div></div>

    <div class="row g-4"><div class="col-12 col-xl-6"><div class="card gym-dashboard-panel h-100"><div class="card-header"><span class="gym-panel-icon text-danger"><i class="bi bi-wallet2"></i></span><div class="gym-panel-heading"><h3 class="card-title">Meu financeiro</h3><small>Próximos vencimentos</small></div><a href="{{ route('student-financial.index') }}" class="gym-view-all">Ver financeiro <i class="bi bi-arrow-right"></i></a></div><div class="card-body gym-due-list">@forelse ($studentPendingTransactions->take(6) as $transaction)<div><span>{{ $transaction->due_date->format('d/m') }}</span><strong>{{ $transaction->description }}</strong><small>R$ {{ number_format((float) $transaction->amount, 2, ',', '.') }}</small></div>@empty<p class="text-muted mb-0">Nenhuma conta pendente.</p>@endforelse</div></div></div><div class="col-12 col-xl-6"><div class="card gym-dashboard-panel h-100"><div class="card-header"><span class="gym-panel-icon text-warning"><i class="bi bi-megaphone-fill"></i></span><div class="gym-panel-heading"><h3 class="card-title">Comunicados</h3><small>Informações importantes da academia</small></div><a href="{{ route('announcements.index') }}" class="gym-view-all">Ver todos <i class="bi bi-arrow-right"></i></a></div><div class="card-body">@forelse ($announcements->take(3) as $announcement)<div class="border-bottom py-2"><strong>{{ $announcement->title }}</strong><small class="d-block text-muted">{{ $announcement->unit?->name ?? 'Todas as unidades' }}</small></div>@empty<p class="text-muted mb-0">Nenhum comunicado disponível.</p>@endforelse</div></div></div></div>
@stop
