@extends('adminlte::page')
@section('title', 'Relatórios')
@section('content_header')
    <div class="d-flex justify-content-between align-items-center"><h1>Relatórios</h1><div class="d-flex gap-2"><a href="{{ route('reports.export', request()->only(['type', 'from', 'to', 'unit_id'])) }}" class="btn btn-success"><i class="bi bi-filetype-csv"></i> CSV</a><a href="{{ route('reports.pdf', request()->only(['type', 'from', 'to', 'unit_id'])) }}" target="_blank" class="btn btn-danger"><i class="bi bi-filetype-pdf"></i> PDF</a></div></div>
@stop
@section('content')
    <x-alerts />
    <div class="card mb-3"><div class="card-body"><form method="GET" action="{{ route('reports.index') }}" class="row g-2 align-items-end"><div class="col-12 col-md-3"><label class="form-label">Relatório</label><select name="type" class="form-select"><option value="financial" @selected($reportType === 'financial')>Financeiro</option><option value="students" @selected($reportType === 'students')>Alunos</option><option value="enrollments" @selected($reportType === 'enrollments')>Matrículas</option><option value="attendance" @selected($reportType === 'attendance')>Presença</option></select></div><div class="col-6 col-md-2"><label class="form-label">De</label><input type="date" name="from" value="{{ request('from', $from->format('Y-m-d')) }}" class="form-control"></div><div class="col-6 col-md-2"><label class="form-label">Até</label><input type="date" name="to" value="{{ request('to', $to->format('Y-m-d')) }}" class="form-control"></div><div class="col-12 col-md-3"><label class="form-label">Unidade</label><select name="unit_id" class="form-select"><option value="">Todas</option>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected($unitId === $unit->id)>{{ $unit->name }}</option>@endforeach</select></div><div class="col-12 col-md-2"><button class="btn btn-primary w-100"><i class="bi bi-funnel"></i> Filtrar</button></div></form></div></div>
    <div class="row g-3 mb-3"><div class="col-md-4"><div class="card"><div class="card-body"><small class="text-muted">Alunos cadastrados</small><h2>{{ $students }}</h2></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><small class="text-muted">Matrículas criadas</small><h2>{{ $enrollments }}</h2></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><small class="text-muted">Presenças registradas</small><h2>{{ $attendance }}</h2></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><small class="text-muted">Receitas pagas</small><h3>R$ {{ number_format((float) $income, 2, ',', '.') }}</h3></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><small class="text-muted">Despesas pagas</small><h3>R$ {{ number_format((float) $expenses, 2, ',', '.') }}</h3></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><small class="text-muted">Inadimplência</small><h3>R$ {{ number_format((float) $overdue, 2, ',', '.') }}</h3></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><small class="text-muted">Resultado</small><h3>R$ {{ number_format((float) $income - (float) $expenses, 2, ',', '.') }}</h3></div></div></div></div>
    <div class="card"><div class="card-header"><h3 class="card-title mb-0">Resultados do relatório</h3></div><div class="card-body table-responsive"><table class="table table-hover align-middle"><thead><tr>@foreach($reportHeaders as $header)<th>{{ $header }}</th>@endforeach</tr></thead><tbody>@forelse($reportRows as $row)<tr>@foreach($row as $value)<td>{{ $value }}</td>@endforeach</tr>@empty<tr><td colspan="{{ count($reportHeaders) }}" class="text-center text-muted">Nenhum registro encontrado para os filtros informados.</td></tr>@endforelse</tbody></table></div></div>
@stop
