@extends('adminlte::page')
@section('title', 'Funcionários')
@push('css')
<style>
@media (max-width:767.98px){.employees-header{align-items:stretch!important;flex-direction:column;gap:.75rem}.employees-header .btn{width:100%}.employees-table thead{display:none}.employees-table tbody tr{display:block;border-bottom:1px solid var(--bs-border-color);padding:.75rem}.employees-table tbody td{display:flex;justify-content:space-between;gap:1rem;border:0;padding:.4rem 0;text-align:right}.employees-table tbody td::before{content:attr(data-label);color:var(--bs-secondary-color);font-weight:600;text-align:left}.employees-table tbody td:last-child{justify-content:flex-end}.employees-table tbody td:last-child::before{display:none}.employees-table tbody td .btn{width:100%}.employees-pagination{overflow-x:auto}}
</style>
@endpush
@section('content_header')<div class="employees-header d-flex justify-content-between align-items-center"><h1>Funcionários</h1><a href="{{ route('employees.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg"></i> Novo funcionário</a></div>@stop
@section('content')<x-alerts /><div class="card mb-3"><div class="card-body"><form method="GET" action="{{ route('employees.index') }}" class="row g-2 align-items-end"><div class="col-12 col-md-6"><label for="search" class="form-label">Buscar</label><input id="search" name="search" value="{{ request('search') }}" class="form-control" placeholder="Nome ou e-mail"></div><div class="col-12 col-md-3"><label for="active" class="form-label">Status</label><select id="active" name="active" class="form-select"><option value="">Todos</option><option value="1">Ativos</option><option value="0">Inativos</option></select></div><div class="col-12 col-md-3 d-flex gap-2"><button class="btn btn-primary flex-grow-1">Filtrar</button><a href="{{ route('employees.index') }}" class="btn btn-outline-secondary">Limpar</a></div></form></div></div><div class="card"><div class="card-body table-responsive"><table class="employees-table table table-hover mb-0"><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Unidade</th><th>Status</th><th class="text-end">Ações</th></tr></thead><tbody>@forelse($employees as $employee)<tr><td data-label="Nome">{{ $employee->name }}</td><td data-label="E-mail">{{ $employee->email }}</td><td data-label="Perfil">{{ ucfirst($employee->role?->value ?? '-') }}</td><td data-label="Unidade">{{ $employee->unit?->name ?? '-' }}</td><td data-label="Status"><span class="badge text-bg-{{ $employee->active ? 'success' : 'secondary' }}">{{ $employee->active ? 'Ativo' : 'Inativo' }}</span></td><td data-label="Ações" class="text-end">@if($employee->employeeProfile)<a href="{{ route('employees.show', $employee->employeeProfile) }}" class="btn btn-sm btn-outline-primary"><i class="bi bi-eye"></i> Visualizar</a>@else<span class="text-muted">Sem perfil</span>@endif</td></tr>@empty<tr><td colspan="6" class="text-center">Nenhum funcionário cadastrado.</td></tr>@endforelse</tbody></table></div><div class="card-footer"><div class="employees-pagination d-flex justify-content-end">{{ $employees->links() }}</div></div></div>@stop
